# Generated by Django 2.2.3 on 2019-07-17 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_stat_checker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_is_active',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.CheckConstraint(check=models.Q(player_is_active__gte=0), name='player_is_active_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.CheckConstraint(check=models.Q(player_is_active__lte=1), name='player_is_active_lte_1'),
        ),
    ]
