# Generated by Django 2.2.3 on 2019-07-17 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_stat_checker', '0002_auto_20190717_1927'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='player',
            name='player_is_active_gte_0',
        ),
        migrations.RemoveConstraint(
            model_name='player',
            name='player_is_active_lte_1',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='player_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='player_full_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='player_is_active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='player_last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='player_num_stats',
            new_name='num_stats',
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.CheckConstraint(check=models.Q(is_active__gte=0), name='is_active_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.CheckConstraint(check=models.Q(is_active__lte=1), name='is_active_lte_1'),
        ),
    ]
