# Generated by Django 2.2.3 on 2019-07-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_stat_checker', '0003_auto_20190717_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerGeneralStatRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField(default=0)),
                ('stat_cid', models.IntegerField(default=0)),
                ('season_id', models.CharField(max_length=15, verbose_name='Year')),
                ('team_abbreviation', models.CharField(max_length=25)),
                ('player_age', models.IntegerField(default=0)),
                ('gp', models.IntegerField(default=0, verbose_name='Games Played')),
                ('gs', models.CharField(max_length=25, verbose_name='Games Started')),
                ('minp', models.FloatField(default=0, verbose_name='Minutes Played')),
                ('fgm', models.IntegerField(default=0, verbose_name='Field Goals Made')),
                ('fga', models.IntegerField(default=0, verbose_name='Field Goals Attempted')),
                ('fg_pct', models.IntegerField(default=0, verbose_name='Field Foal Percentage')),
                ('fg3m', models.IntegerField(default=0, verbose_name='3 Point Field Goals Made')),
                ('fg3a', models.IntegerField(default=0, verbose_name='3 Point Field Goals Attempted')),
                ('fg3_pct', models.CharField(max_length=25, verbose_name='3 Point Field Goals Percentage')),
                ('ftm', models.IntegerField(default=0, verbose_name='Free Throws Made')),
                ('fta', models.IntegerField(default=0, verbose_name='Free Throws Attempted')),
                ('ft_pct', models.FloatField(default=0, verbose_name='Free Throw Percentage')),
                ('oreb', models.CharField(max_length=25, verbose_name='Offensive Rebounds')),
                ('dreb', models.CharField(max_length=25, verbose_name='Defensive Rebounds')),
                ('reb', models.IntegerField(default=0, verbose_name='Rebounds')),
                ('ast', models.IntegerField(default=0, verbose_name='Assists')),
                ('stl', models.CharField(max_length=25, verbose_name='Steals')),
                ('blk', models.CharField(max_length=25, verbose_name='Blocks')),
                ('tov', models.CharField(max_length=25, verbose_name='Turnovers')),
                ('pf', models.IntegerField(default=0, verbose_name='Personal Fouls')),
                ('pts', models.IntegerField(default=0, verbose_name='Points')),
            ],
            options={
                'ordering': ['stat_cid'],
            },
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['last_name', 'first_name']},
        ),
    ]
