# Generated by Django 2.2.3 on 2019-07-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_stat_checker', '0004_auto_20190723_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playergeneralstatrecord',
            name='gs',
            field=models.IntegerField(default=0, verbose_name='Games Started'),
        ),
    ]
