# Generated by Django 2.2.3 on 2019-07-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_stat_checker', '0005_auto_20190723_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playergeneralstatrecord',
            name='blk',
            field=models.FloatField(default=0, verbose_name='Blocks'),
        ),
        migrations.AlterField(
            model_name='playergeneralstatrecord',
            name='dreb',
            field=models.FloatField(default=0, verbose_name='Defensive Rebounds'),
        ),
        migrations.AlterField(
            model_name='playergeneralstatrecord',
            name='fg3_pct',
            field=models.FloatField(default=0, verbose_name='3 Point Field Goals Percentage'),
        ),
        migrations.AlterField(
            model_name='playergeneralstatrecord',
            name='oreb',
            field=models.FloatField(default=0, verbose_name='Offensive Rebounds'),
        ),
        migrations.AlterField(
            model_name='playergeneralstatrecord',
            name='stl',
            field=models.FloatField(default=0, verbose_name='Steals'),
        ),
        migrations.AlterField(
            model_name='playergeneralstatrecord',
            name='tov',
            field=models.FloatField(default=0, verbose_name='Turnovers'),
        ),
    ]
