# Generated by Django 2.2.3 on 2019-07-24 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba_stat_checker', '0006_auto_20190724_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playergeneralstatrecord',
            options={'ordering': ['player_id', 'stat_cid']},
        ),
    ]
