# Generated by Django 2.2.3 on 2019-07-25 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nba_stat_checker', '0007_auto_20190724_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playergeneralstatrecord',
            name='player_id',
        ),
        migrations.AddField(
            model_name='playergeneralstatrecord',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nba_stat_checker.Player'),
        ),
    ]
