# Generated by Django 2.2.3 on 2019-07-25 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba_stat_checker', '0008_auto_20190725_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playergeneralstatrecord',
            name='fg_pct',
        ),
    ]
