# Generated by Django 2.2.3 on 2019-08-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_stat_checker', '0009_remove_playergeneralstatrecord_fg_pct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
            ],
        ),
    ]
