# Generated by Django 2.2.3 on 2019-08-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_stat_checker', '0012_auto_20190805_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_abbreviation',
            field=models.CharField(default='N/A', max_length=5),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
