# Generated by Django 2.2.3 on 2019-08-08 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba_stat_checker', '0013_auto_20190806_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name']},
        ),
    ]
